version: "3.3"

services:

  kb:
    image: linkeddatacenter/sdaas-rdfstore
    ports:
      - "9999:8080"
  
  cli:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - kb
    volumes:
      - .:/workspace

  tests:
    build: .
    command: sdaas -c "bats tests/{unit,functional,system}"
    depends_on:
      - kb
    volumes:
      - .:/workspace
