version: "3.3"

services:

  kb:
    image: linkeddatacenter/sdaas-rdfstore
    ports:
      - "9999:8080"
  
  cli:
    image: linkeddatacenter/sdaas-ce:dev
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - kb
    volumes:
      - .:/workspace