# Copyright (C) 2019-2020 LinkedData.Center - All Rights Reserved
# Permission to copy and modify is granted under the MIT license
FROM  linkeddatacenter/sdaas-rdfstore:2.0.0

LABEL authors="enrico@linkeddata.center"

USER root
RUN set -xe ; \
	apt-get update ; \
	apt-get install -y --no-install-recommends curl gettext 
	
RUN apt-get install -y bats sudo 

# Allow jetty to became su (no password)
RUN echo "jetty\njetty" | passwd jetty; usermod -aG sudo jetty

USER jetty
WORKDIR  /workspace

ENV SD_REASONER_ENDPOINT http://localhost:8080/sdaas
ENV PATH="/workspace/scripts:${PATH}"
