services:

  kb:
    image: linkeddatacenter/sdaas-rdfstore:2.2.1
    ports:
      - "9999:8080"
  
  cli:
    image: linkeddatacenter/sdaas-ce:dev
    build:    
      context: .
      args:
        - MODE=${MODE:-test}  # define MODE=prod to unload test support
    stdin_open: true
    tty: true
    depends_on:
      - kb
    volumes:
      - .:/workspace
