#!/usr/bin/env bash


function USAGE {
	>&2 cat <<-EOT
		Smart Data as a Service (SDaaS) platform community edition
		Copyright (C) 2018 http://linkeddata.center/
			
		startup options:
		
		--foreground
			execute the platform in foreground
		
		--readonly
		   disallow mutations in graph database
	EOT
	exit 1
}


### Parse command line options
__parsed=$(getopt -options="" --longoptions=foreground,readonly --name "$0" -- "$@") || USAGE
eval set -- "$__parsed"
unset __parsed 

FOREGROUND=0
READONLY=0
while true; do
	case "$1" in
	    --foreground)
	    	FOREGROUND=1
            shift
	    	;;
		--readonly)
	    	READONLY=1
            shift
	    	;;
        --)
            shift
            break
        ;;
	    *)
	        USAGE
	    ;;
	esac
done

if [  $READONLY -eq 1 ]; then 
	cp /readonly-web.xml ${JETTY_WEBAPPS}/sdaas/WEB-INF/web.xml
else
	cp /writable-web.xml ${JETTY_WEBAPPS}/sdaas/WEB-INF/web.xml
fi

STARTUP_CMD="sudo -u jetty java -jar /usr/local/jetty/start.jar STOP.PORT=28282 STOP.KEY=secret"

echo -n "SDaaS engine starting..."

if [ $FOREGROUND -eq 1 ]; then
	echo "Press ctrl-c to stop."
	cd /var/lib/jetty &&  $STARTUP_CMD
else
	echo "as daemon"
	cd /var/lib/jetty &&  $STARTUP_CMD &
	sleep 10
fi